<a href="https://colab.research.google.com/github/rinarina0328/Document001/blob/master/ensyuu1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
ts, xs = np.loadtxt('doso_ch1.txt', unpack = True)

In [3]:
ts

array([0.26 , 0.262, 0.264, ..., 4.754, 4.756, 4.758])

In [4]:
xs

array([8. , 8.8, 8.8, ..., 4.8, 4.8, 4.8])

In [5]:
ts, xs

(array([0.26 , 0.262, 0.264, ..., 4.754, 4.756, 4.758]),
 array([8. , 8.8, 8.8, ..., 4.8, 4.8, 4.8]))

In [6]:
print(ts[:3])

[0.26  0.262 0.264]


In [0]:
h = ts[1] - ts[0]

In [8]:
h

0.0020000000000000018

In [0]:
ws = np.arange(0,10,0.01)
Re = np.empty(ws.size)
Im = np.empty(ws.size)
Fs = np.empty(ws.size)

In [0]:
n = 0
for w in ws:
  Re[n]=xs[n]*np.cos(ws[n]*ts[n])*h
  Im[n]=xs[n]*np.sin(ws[n]*ts[n])*h
  Fs[n]=np.sqrt(Re[n]*Re[n]+Im[n]*Im[n])
  n += 1

In [11]:
Fs

array([0.016 , 0.0176, 0.0176, 0.0176, 0.0176, 0.0192, 0.0176, 0.0192,
       0.0192, 0.0208, 0.0208, 0.0208, 0.0224, 0.0208, 0.0208, 0.0224,
       0.024 , 0.024 , 0.024 , 0.024 , 0.024 , 0.024 , 0.024 , 0.0256,
       0.0256, 0.0256, 0.0256, 0.0256, 0.0256, 0.0256, 0.0272, 0.0272,
       0.0272, 0.0288, 0.0288, 0.0288, 0.0288, 0.0272, 0.0288, 0.0288,
       0.0304, 0.0304, 0.0304, 0.0304, 0.0304, 0.032 , 0.032 , 0.032 ,
       0.032 , 0.032 , 0.032 , 0.0336, 0.0336, 0.0336, 0.0336, 0.0336,
       0.0336, 0.0336, 0.0336, 0.0336, 0.0336, 0.0368, 0.0368, 0.0368,
       0.0368, 0.0368, 0.0352, 0.0368, 0.0368, 0.0352, 0.0368, 0.0368,
       0.0368, 0.0368, 0.0368, 0.0384, 0.0384, 0.0384, 0.0384, 0.0384,
       0.0368, 0.0368, 0.0384, 0.0384, 0.0368, 0.0384, 0.0384, 0.0384,
       0.0384, 0.0368, 0.0384, 0.0384, 0.0384, 0.0384, 0.0384, 0.04  ,
       0.04  , 0.04  , 0.04  , 0.04  , 0.04  , 0.04  , 0.04  , 0.04  ,
       0.04  , 0.04  , 0.04  , 0.04  , 0.0416, 0.0416, 0.04  , 0.04  ,
      

In [0]:
np.savetxt('out.txt', np.c_[ws, Fs])